apiVersion: v1
kind: Service
metadata:
  name: color-svc
  labels:
    app: web
spec:
  selector:
    app: web
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-server
        image: raftx/sample-web:yellow
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
