apiVersion: v1
kind: Service
metadata:
  name: goldengoose
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: goldengoose
    track: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldengoose
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: goldengoose
        track: prod
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google_containers/echoserver:1.10
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: goldengoose
      track: prod
