apiVersion: v1
kind: Pod
metadata:
  name: gray
  labels:
    color: gray
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: special
            operator: In
            values:
            - app
  containers:
  - name: gray
    image: raftx/sample-web:v1
