apiVersion: v1
kind: Pod
metadata:
  name: front-end
  labels:
    color: client-go
spec:
  containers:
  - image: raftx/sample-client:label-svc
    name: client-go
    imagePullPolicy: Always
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: back-end-svc
#spec:
#  selector:
#    app: back-end
#  ports:
#  - name: http
#    port: 8080
#    targetPort: 8080
#---
apiVersion: v1
kind: Pod
metadata:
  name: back-end
  labels:
    app: back-end
spec:
  containers:
  - image: raftx/sample-web:v4
    name: back-end
    ports:
    - containerPort: 8080
