apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    app: web
spec:
  volumes:
  - name: varfile
    configMap:
      name: myvars
      items:
      - key: var.txt
        path: var.txt
  containers:
  - image: raftx/sample-web:configmap
    name: sample-web
    env:
    - name: MYVAR
      valueFrom:
        configMapKeyRef:
          key: MYVAR
          name: myvars
    - name: MYSECRET
      valueFrom:
        secretKeyRef:
          key: secretenv
          name: mysecret
    volumeMounts:
    - name: varfile
      mountPath: /data/
