apiVersion: apps/v1
kind: deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingsservice
  template:
    metadata:
      labels:
        app: shippingsservice
    spec:
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.2.1
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
#        resources:
#          requests:
#            cpu: 100m
#            memory: 64Mi
#          limits:
#            cpu: 200m
#            memory: 128Mi
