apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hpa-test
  name: hpa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hpa-test
    spec:
      containers:
      - image: busybox:1.33.0
        name: busybox
        command: ["/bin/sh", "-c", "sleep 6000"]
        resources:
          requests:
            cpu: "50m"
status: {}
